version: "3"
services:
  # db:
  #   image: mariadb
  #   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #     - /tmp/dockerdir:/etc/mysql/conf.d/
  #   ports:
  #     - 3306:3306
  db:
    image: postgres:12.3
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 3306:3306
  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp
      - ./backend/vendor/bundle:/myapp/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    env_file:
      - .envrc
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "cd react-app && yarn start"
    ports:
      - "8000:3000"
volumes:
  # mysql-data:
  db-data:
